### ISSUE TITLE
Unable to build on Ubuntu 18.04

### ISSUE THREAD

**Issue by sjpschutte** [andrewrk/clashos#1]
Do I need a version of objcopy that understands ARM binaries ?

paul@maya:~/clashos$ **git pull**
Already up to date.

paul@maya:~/clashos$ **zig version**
0.3.0+6df8e4bc

paul@maya:~/clashos$ **zig build**
objcopy: Unable to recognise the format of the input file `zig-cache/clashos'
The following command exited with error code 1:
cd /home/paul/clashos && objcopy zig-cache/clashos -O binary clashos.bin 

Build failed. The following command failed:
/home/paul/.local/share/zig/stage1/artifact/BZdEUw8SP-ul_WQSBa42LmRtuXy81VFGbSx2hjs5H2XRPPQKwt_F21kEdrJXQzli/build /snap/zig/297/zig /home/paul/clashos /home/paul/clashos/zig-cache

paul@maya:~/clashos/zig-cache$ **file clashos**
clashos: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, not stripped

**Comment by raoofha** [comment]
I added ```"-I", "elf64-little",``` after line 33 in ```build.zig``` and it worked. I also installed ```qemu-system-aarch64```

**Comment by sjpschutte** [comment]
Thanks it worked !
