### ISSUE TITLE
error: no member named 'seekForwardFn'

### ISSUE THREAD

**Issue by markfirmware** [andrewrk/clashos#3]
Linux localhost 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64 GNU/Linux

    0.4.0+ddfab40e
    
    zig build
    /root/github.com/andrewrk/clashos/src/debug.zig:84:13: error: no member named 'seekForwardFn' in struct 'std.io.seekable_stream.SeekableStream(anyerror,anyerror)'
    The following command exited with error code 1:
    /root/zig-linux-x86_64-0.4.0/zig build-exe /root/github.com/andrewrk/clashos/src/main.zig --pkg-begin build_options /root/github.com/andrewrk/clashos/zig-cache/clashos_build_options.zig --pkg-end --cache-dir /root/github.com/andrewrk/clashos/zig-cache --name clashos -target aarch64v8-freestanding-eabihf --linker-script src/linker.ld --output-dir zig-cache 
    
    Build failed. The following command failed:
    /root/github.com/andrewrk/clashos/zig-cache/o/kPMAKFevlwnid2qJdXuP67PbCM0TIdbKfjr05A5z0XqxO82FO-h-u_vLbBva1wyD/build /root/zig-linux-x86_64-0.4.0/zig /root/github.com/andrewrk/clashos /root/github.com/andrewrk/clashos/zig-cache

**Comment by andrewrk** [comment]
a804d7daa45e496d939d1f905e1cfdeb5cae2a30
